name: advertising_id
description: A new Flutter plugin.
version: 0.9.0
author: Shinobu Okano <okanoshinobu8@gmail.com>
homepage:

flutter:
  plugin:
    androidPackage: com.os.operando.advertisingid
    pluginClass: AdvertisingIdPlugin

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=1.21.0"
  flutter: ">=0.1.4"